sentinel variable-Add feature
bernicuts/unit-converter pull request #3
Opened 2019-09-01 20:33 UTC by bernicuts

cod ready for first 2 task

2019-09-01 20:43 UTC, bernicuts commented on src/unit_convert.java
> +		boolean varType = true ; // that would be a sentinel variable
sentiner variable

2019-09-01 23:19 UTC, marcelbernic requested changes
Fix everything specified in the comments (reach @marcelbernic if you have any questions). Once everything is fixed we'll merge the code in master (the master is your PROD, we're gonna put this feature in PROD).

2019-09-01 23:19 UTC, marcelbernic commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
this file is generated by eclispe. Normaly this file should exist ONLY on your local repo (on you computer). Think about it, maybe I don't use eclipse (I use IntelliJ IDE) so this file is not pertinent for me (or other developer). For this reason there is a '.gitignore' file  in you git repo. In this file we specify wich files we don't add to push on remote repo (files that we want that git IGNORES). You can specify also a file pattern in git ignore. Read a little bit about gitignore and his purpose. And add this file to gitignore so we don't track it on remote repo. On the web there exists tools to generate some gitignore file (https://www.gitignore.io/) , feel free to explore. You can specify here: java, eclipse, intellij and the tool we'll generate for this file. Still, at this stage is better to write your own .gitingnore file so you better understand. To complete this comment add this file(.classpath) to .gitignore.

2019-09-01 23:19 UTC, marcelbernic commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
Same comment as for the file .casspath

2019-09-01 23:19 UTC, marcelbernic commented on src/unit_convert.java
> +//adaugat metric-converter
Remove this comment

2019-09-01 23:19 UTC, marcelbernic commented on src/unit_convert.java
> +		System.out.println("___the conversion is being started___");
Chose a better (significant) message for the user

2019-09-01 23:19 UTC, marcelbernic commented on src/unit_convert.java
> +		System.out.println("-\\hai sa comparam mere cu pere\\-");
Remove this comment (zero effect on the code and on the user)

2019-09-01 23:19 UTC, marcelbernic commented on src/unit_convert.java
> +		boolean varType = true ; // that would be a sentinel variable
Chose a better name for this variable (significant, meaningful)

2019-09-01 23:19 UTC, marcelbernic commented on src/unit_convert.java
> +
remove this empty line

2019-09-01 23:19 UTC, marcelbernic commented on src/unit_convert.java
> +			catch (Exception e) {
Here you catch ANY exception that is thrown in your try block. Please catch only the exception throwed by 'user_int.nextInt()'. We don't want to generalize a specific problem (that's not a good practice). Ask @marcelbernic  if this comment is not clear.

2019-09-01 23:19 UTC, marcelbernic commented on src/unit_convert.java
> +				System.out.println("value invalid, try again with a number...\n");
Write a better message (think that you are the user... -200 is a number, but maybe this number is not a valid number for our application).

2019-09-02 20:32 UTC, bernicuts reviewed
all is fixed

2019-09-02 20:32 UTC, bernicuts commented on src/unit_convert.java
> +				System.out.println("value invalid, try again with a number...\n");
tre de pus inca un punct

2019-09-02 20:32 UTC, bernicuts commented on src/unit_convert.java
>  	public static void main (String[] args) {
ce face asta

2019-09-02 20:32 UTC, bernicuts commented on src/unit_convert.java
>  		System.out.println("-\\hai sa comparam mere cu pere\\-");
aduce la ecran

2019-09-02 20:32 UTC, bernicuts commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
added git .ignore with content generated on www.gitignore.io

2019-09-02 20:34 UTC, merged